---
title: "Day 10 Viz"
author: "Andre Dextre"
date: "2022-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)
library(sf)
library(lubridate)
```

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

### Make A Heatmap

```{r}
lizards_counts <- lizards %>%
  mutate(date = mdy(date)) %>%
  count(year = year(date), common_name) %>%
  drop_na()
```

```{r}
ggplot(data = lizards_counts, aes(x = year,
                                  y = common_name)) +
  geom_tile(aes(fill = n), show.legend = FALSE) +
  geom_text(aes(label = n), color = "white", size = 3) +
  scale_fill_gradientn(colors = c("navy", "red", "orange")) +
  theme_minimal()
```


### Beeswarm Plot

```{r}
whiptails <- lizards %>%
  filter(common_name == "western whiptail") %>%
  drop_na(total_length, weight)
```


```{r}
whiptail_bee <- ggplot(data = whiptails, aes(x = sex,
                             y = weight)) +
  geom_beeswarm() +
  geom_boxplot(fill = NA)
```

### Marginal Plot

- Plot total length (x-axis) vs weight (y-axis), with point color dependent on sex.

```{r}
whiptail_plot <- ggplot(data = whiptails, aes(x = total_length,
                             y = weight)) +
  geom_point(aes(color = sex)) +
  theme(legend.position = "bottom")

ggMarginal(whiptail_plot, type = "boxplot", groupColour = TRUE)
```

### Patchwork

```{r}
((whiptail_bee + whiptail_plot) / whiptail_bee) + whiptail_plot & theme_dark()
```















