---
title: "Day 8 Notes"
author: "Andre Dextre"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)
library(sf)
```

### Read in lizard data

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards) +
  geom_point(aes(x = total_length,
                           y = weight))
```

Create a histogram of total lengths for all lizards in the dataset.

```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(color = "orange",
                 fill = "purple",
                 size = 1,
                 linetype = "dotted")
```

```{r}
ggplot(data = lizards, aes(x = total_length,
                           y = weight)) +
  geom_point(shape = 22,
             color = "cyan4",
             fill = "yellow",
             size = 4,
             alpha = 0.4
  )
```

```{r}
ggplot(data = lizards, aes(x = total_length,
                           y = weight)) +
  geom_point(aes(color = common_name,
                 size = total_length),
             alpha = 0.5) +
  theme_minimal()
```

```{r}
ggplot(data = lizards, aes(x = total_length,
                           y = weight)) +
  geom_point() +
  facet_wrap(~common_name, scales = "free")
```

```{r}
lizard_count <- lizards %>%
  group_by(common_name) %>%
  summarize(counts = n())

lizard_counts <- lizards %>%
  count(common_name)

ggplot(data = lizard_count, aes(y = common_name,
                                x = counts)) +
  geom_col()
```


```{r}
ggplot(data = lizard_count, aes(y = fct_reorder(common_name, counts),
                                x = counts)) +
  geom_col()
```

Create scatter plots, faceted by species, for total length vs weight. The color and shape of points should differ based on the species (common_name). Change the theme. Make each faceted panel have flexible axis limits (scales should be free).

```{r}
ggplot(data = lizards, aes(x = total_length,
                           y = weight)) +
  geom_point(aes(color = common_name),
             alpha = 0.6,
             size = 1) +
  theme_minimal() +
  facet_wrap(~common_name, scales = "free")
```

